@startuml updateWriting

actor Teacher
participant "WritingServiceImpl" as WritingService
participant "BaseServiceImpl" as BaseService
participant "WritingRepository" as Repository


== Lược đồ tuần tự chức năng chỉnh sửa bài học viết ==
Teacher -> WritingService: update(dto, id)
activate WritingService

WritingService -> BaseService: update(dto, id) << Inherited from Parent >>
activate BaseService
activate WritingService

BaseService -> BaseService: isExist(id) << Inherited from Parent >>
BaseService -> WritingService: convertToEntity(dto) << Overridden >>
WritingService --> BaseService: WritingEntity
deactivate WritingService

BaseService -> Repository: save(updatedEntity)
activate Repository
Repository --> BaseService: Updated WritingEntity
deactivate Repository

BaseService -> WritingService: convertToDTO(updatedEntity) << Overridden >>
WritingService --> BaseService: Updated WritingDTO
deactivate BaseService

WritingService --> Teacher: Updated WritingDTO
deactivate WritingService

@enduml
