@startuml submitTestMixing
actor "Student" as Student
participant "SubmitTestMixingAnswerServiceImpl" as SubmitTestMixingService
participant "BaseServiceImpl" as BaseService
participant "TestMixingAnswerRepository" as Repository

== Lược đồ tuần tự chức năng nộp câu trả lời bài kiểm tra về từ vựng và ngữ pháp  ==
Student -> SubmitTestMixingService: submitTestMixingAnswer(dto)
activate SubmitTestMixingService

SubmitTestMixingService -> BaseService: create(dto) << Inherited from Parent >>
activate BaseService

BaseService -> SubmitTestMixingService: convertToEntity(dto) << Overridden >>
activate SubmitTestMixingService
SubmitTestMixingService --> BaseService: TestMixingAnswerEntity
deactivate SubmitTestMixingService

BaseService -> Repository: save(entity)
activate Repository
Repository --> BaseService: Saved TestMixingAnswerEntity
deactivate Repository

BaseService -> SubmitTestMixingService: convertToDTO(savedEntity) << Overridden >>
activate SubmitTestMixingService
SubmitTestMixingService --> BaseService: TestMixingAnswerDTO
deactivate SubmitTestMixingService

BaseService --> SubmitTestMixingService: Saved TestMixingAnswerDTO
deactivate BaseService

SubmitTestMixingService --> Student: TestMixingAnswerDTO
deactivate SubmitTestMixingService
@enduml
