@startuml submitTestListening
actor "Student" as Student
participant "SubmitTestListeningServiceImpl" as SubmitTestListeningService
participant "BaseServiceImpl" as BaseService
participant "TestListeningAnswerRepository" as Repository

== Lược đồ tuần tự chức năng nộp câu trả lời bài kiểm tra về nghe ==
Student -> SubmitTestListeningService: submitTestListeningAnswer(dto)
activate SubmitTestListeningService

SubmitTestListeningService -> BaseService: create(dto) << Inherited from Parent >>
activate BaseService

BaseService -> SubmitTestListeningService: convertToEntity(dto) << Overridden >>
activate SubmitTestListeningService
SubmitTestListeningService --> BaseService: TestListeningAnswerEntity
deactivate SubmitTestListeningService

BaseService -> Repository: save(entity)
activate Repository
Repository --> BaseService: Saved TestListeningAnswerEntity
deactivate Repository

BaseService -> SubmitTestListeningService: convertToDTO(savedEntity) << Overridden >>
activate SubmitTestListeningService
SubmitTestListeningService --> BaseService: TestListeningAnswerDTO
deactivate SubmitTestListeningService

BaseService --> SubmitTestListeningService: Saved TestListeningAnswerDTO
deactivate BaseService

SubmitTestListeningService --> Student: TestListeningAnswerDTO
deactivate SubmitTestListeningService
@enduml
