@startuml submitTestReading
actor "Student" as Student
participant "SubmitTestReadingAnswerServiceImpl" as SubmitTestReadingService
participant "BaseServiceImpl" as BaseService
participant "TestReadingAnswerRepository" as Repository

== Lược đồ tuần tự chức năng nộp câu trả lời bài kiểm tra về đọc ==
Student -> SubmitTestReadingService: submitTestReadingAnswer(dto)
activate SubmitTestReadingService

SubmitTestReadingService -> BaseService: create(dto) << Inherited from Parent >>
activate BaseService

BaseService -> SubmitTestReadingService: convertToEntity(dto) << Overridden >>
activate SubmitTestReadingService
SubmitTestReadingService --> BaseService: TestReadingAnswerEntity
deactivate SubmitTestReadingService

BaseService -> Repository: save(entity)
activate Repository
Repository --> BaseService: Saved TestReadingAnswerEntity
deactivate Repository

BaseService -> SubmitTestReadingService: convertToDTO(savedEntity) << Overridden >>
activate SubmitTestReadingService
SubmitTestReadingService --> BaseService: TestReadingAnswerDTO
deactivate SubmitTestReadingService

BaseService --> SubmitTestReadingService: Saved TestReadingAnswerDTO
deactivate BaseService

SubmitTestReadingService --> Student: TestReadingAnswerDTO
deactivate SubmitTestReadingService
@enduml
