@startuml updateReadingAnswer

actor Teacher
participant "ReadingAnswerServiceImpl" as ReadingAnswerService
participant "BaseServiceImpl" as BaseService
participant "ReadingAnswerRepository" as Repository

== Lược đồ tuần tự chức năng chỉnh sửa câu trả lời  cho câu hỏi bài học đọc ==
Teacher -> ReadingAnswerService: update(dto, id)
activate ReadingAnswerService

ReadingAnswerService -> BaseService: update(dto, id) << Inherited from Parent >>
activate BaseService

BaseService -> BaseService: isExist(id)
BaseService -> ReadingAnswerService: convertToEntity(dto) << Overridden >>
activate ReadingAnswerService
ReadingAnswerService -> ReadingAnswerService: convertToEntity(dto)
ReadingAnswerService --> BaseService: Converted ReadingAnswerEntity
deactivate ReadingAnswerService

BaseService -> Repository: save(updatedEntity)
activate Repository
Repository --> BaseService: Updated ReadingAnswerEntity
deactivate Repository

BaseService -> ReadingAnswerService: convertToDTO(updatedEntity) << Overridden >>
activate ReadingAnswerService
ReadingAnswerService -> ReadingAnswerService: convertToDTO(updatedEntity)
ReadingAnswerService --> BaseService: Updated ReadingAnswerDTO
deactivate ReadingAnswerService

BaseService --> ReadingAnswerService: Updated ReadingAnswerDTO
deactivate BaseService

ReadingAnswerService --> Teacher: Updated ReadingAnswerDTO
deactivate ReadingAnswerService

@enduml
