@startuml updateReadingQuestion

actor Teacher
participant "ReadingQuestionServiceImpl" as ReadingQuestionService
participant "BaseServiceImpl" as BaseService
participant "ReadingQuestionRepository" as Repository


== Lược đồ tuần tự chức năng chỉnh sửa câu hỏi bài học đọc ==
Teacher -> ReadingQuestionService: update(dto, id)
activate ReadingQuestionService

ReadingQuestionService -> ReadingQuestionService: isSerialUnique(dto.getReadingId(), dto.getSerial(), id)
ReadingQuestionService -> BaseService: update(dto, id) << Inherited from Parent >>
activate BaseService

BaseService -> BaseService: isExist(id)
BaseService -> ReadingQuestionService: convertToEntity(dto) << Overridden >>
activate ReadingQuestionService
ReadingQuestionService -> ReadingQuestionService: convertToEntity(dto)
ReadingQuestionService --> BaseService: Converted ReadingQuestionEntity
deactivate ReadingQuestionService

BaseService -> Repository: save(updatedEntity)
activate Repository
Repository --> BaseService: Updated ReadingQuestionEntity
deactivate Repository

BaseService -> ReadingQuestionService: convertToDTO(updatedEntity) << Overridden >>
activate ReadingQuestionService
ReadingQuestionService -> ReadingQuestionService: convertToDTO(updatedEntity)
ReadingQuestionService --> BaseService: Converted ReadingQuestionDTO
deactivate ReadingQuestionService

BaseService --> ReadingQuestionService: Updated ReadingQuestionDTO
deactivate BaseService

ReadingQuestionService --> Teacher: Updated ReadingQuestionDTO
deactivate ReadingQuestionService

@enduml
