@startuml ConvertToDTO

participant "BaseServiceImpl" as BSI
participant "ReadingServiceImpl" as RS

== Convert Reading Entity to DTO ==
BSI -> RS: convertToDTO(entity)
note right: convertToDTO được triển khai trong ReadingServiceImpl
activate RS
RS --> BSI: ReadingDTO
deactivate RS

@enduml
