@startuml findByIdReadingService

actor Student
participant "ReadingServiceImpl" as ReadingService
participant "BaseServiceImpl" as BaseService
participant "ReadingRepository" as Repository


== Lược đồ tuần tự chức năng tìm kiếm bài đọc theo Id ==
Student -> ReadingService: findById(id)
activate ReadingService

ReadingService -> BaseService: findById(id) << Inherited from Parent >>
activate BaseService
BaseService -> BaseService: isExist(id)
BaseService -> Repository: findById(id)
activate Repository
Repository --> BaseService: ReadingEntity
deactivate Repository

BaseService -> ReadingService: convertToDTO(entity) << Overridden >>
activate ReadingService
ReadingService -> ReadingService: convertToDTO(entity)
ReadingService --> BaseService: ReadingDTO
deactivate ReadingService

BaseService --> ReadingService: DTO
deactivate BaseService

ReadingService --> Student: DTO
deactivate ReadingService

@enduml
