@startuml deleteSpeaking

actor Teacher
participant "SpeakingServiceImpl" as SpeakingService
participant "BaseServiceImpl" as BaseService
participant "SpeakingConversationServiceImpl" as SpeakingConversationService

== Lược đồ tuần tự chức năng xoá bài học nói ==
Teacher -> SpeakingService: delete(id)
activate SpeakingService

SpeakingService -> SpeakingConversationService: findBySpeakingId(id)
activate SpeakingConversationService
SpeakingConversationService --> SpeakingService: List<SpeakingConversationDTO>
deactivate SpeakingConversationService

loop Delete Speaking Conversations
    SpeakingService -> SpeakingConversationService: delete(speakingConversationDTO.getId())
    activate SpeakingConversationService
    SpeakingConversationService --> SpeakingService: Deleted SpeakingConversationDTO
    deactivate SpeakingConversationService
end

SpeakingService -> BaseService: delete(id) << Inherited from Parent >>
activate BaseService

BaseService --> SpeakingService: Deleted Speaking entity
deactivate BaseService

SpeakingService --> Teacher: Deleted Speaking entity
deactivate SpeakingService

@enduml
