@startuml ConvertToDTO

participant "BaseServiceImpl" as BSI
participant "ListeningServiceImpl" as LS

== Convert Listening Entity to DTO ==
BSI -> LS: convertToDTO(entity)
note right: convertToDTO được triển khai trong ListeningServiceImpl
activate LS
LS --> BSI: ListeningDTO
deactivate LS

@enduml
