@startuml
actor Teacher
participant "System" as System
participant "Lesson Model" as lM

Teacher -> System: Request to add lesson
activate System
System -> Teacher: Require lesson data
Teacher -> System: Send lesson data
System -> lM: Send lesson data
activate lM
lM -> lM: Create lesson
lM --> System: Lesson created data
deactivate lM
System -> Teacher: Lesson created data
deactivate System
@enduml
