@startuml
actor Teacher
participant "System" as System
participant "Test Model" as tM

Teacher -> System: Request to add test
activate System
System -> Teacher: Require test data
Teacher -> System: Send test data
System -> tM: Send test data
activate tM
tM -> tM: Create test
tM --> System: Test created data
deactivate tM
System -> Teacher: Test created data
deactivate System
@enduml
