@startuml
actor Teacher
participant "System" as System
participant "Lesson Model" as lM

Teacher -> System: Request to delete lesson
activate System
System -> lM: Send lesson ID for deletion
activate lM
lM -> lM: Delete lesson
lM -> System: Lesson deletion confirmation
deactivate lM
System -> Teacher: Lesson deleted successfully
deactivate System
@enduml
