@startuml
actor Student
participant "System" as System
participant "Geimni API" as Geimni

Student -> System: Submit speaking
activate System
System -> Geimni: Send speaking data for scoring
activate Geimni
Geimni -> Geimni: Process scoring and generate comments
Geimni --> System: Return score and comments
deactivate Geimni
System -> Student:  score and comments
deactivate System
@enduml
