@startuml
actor User
participant "System" as System
participant "Test Model" as tM

User -> System: Request  list of tests
activate System
System -> tM: Fetch test list
activate tM
tM --> System: Return test list
deactivate tM
System -> User:  test list
deactivate System
@enduml
