@startuml
actor Admin
participant "System" as System
participant "User Model" as uM

Admin -> System: Request  list of user
activate System
System -> uM: Fetch user list
activate uM
uM -> System:  user list
deactivate uM
System -> Admin:  user list
deactivate System
@enduml
