@startuml
actor User
participant "System" as System
participant "Lesson Model" as lM

User -> System: Request lesson detail
activate System
System -> lM: Fetch lesson detail
activate lM
lM -> System: Lesson detail data
deactivate lM
System -> User:  Lesson detail data
deactivate System
@enduml
