@startuml deleteListening

actor Teacher
participant "ListeningServiceImpl" as ListeningService
participant "BaseServiceImpl" as BaseService
participant "ListeningQuestionServiceImpl" as ListeningQuestionService
participant "ListenAndWriteAWordServiceImpl" as ListenAndWriteAWordService

== 	Lược đồ tuần tự chức năng xoá bài học nghe ==
Teacher -> ListeningService: delete(id)
activate ListeningService

ListeningService -> BaseService: isExist(id) << Inherited from Parent >>
activate BaseService
BaseService --> ListeningService: Entity exists
deactivate BaseService

ListeningService -> ListeningQuestionService: findByListeningId(id)
activate ListeningQuestionService
ListeningQuestionService --> ListeningService: List<ListeningQuestionDTO>
deactivate ListeningQuestionService

loop Delete Listening Questions
    ListeningService -> ListeningQuestionService: delete(questionDTO.getId())
    activate ListeningQuestionService
    ListeningQuestionService --> ListeningService: Deleted ListeningQuestionDTO
    deactivate ListeningQuestionService
end

ListeningService -> ListenAndWriteAWordService: findByListeningId(id)
activate ListenAndWriteAWordService
ListenAndWriteAWordService --> ListeningService: List<ListenAndWriteAWordDTO>
deactivate ListenAndWriteAWordService

loop Delete ListenAndWriteAWord
    ListeningService -> ListenAndWriteAWordService: delete(listenAndWriteAWordDTO.getId())
    activate ListenAndWriteAWordService
    ListenAndWriteAWordService --> ListeningService: Deleted ListenAndWriteAWordDTO
    deactivate ListenAndWriteAWordService
end

ListeningService -> BaseService: delete(id) << Inherited from Parent >>
activate BaseService
BaseService --> ListeningService: Deleted entity
deactivate BaseService

ListeningService --> Teacher: Deleted Listening entity
deactivate ListeningService

@enduml
