@startuml createTopicAnswer

actor Teacher
participant "TopicAnswerServiceImpl" as TopicAnswerService
participant "BaseServiceImpl" as BaseService
participant "TopicAnswerRepository" as Repository
participant "TopicAnswerDTO" as DTO
participant "TopicAnswerEntity" as Entity

== Lược đồ tuần tự chức năng tạo đáp án chủ đề ==
Teacher -> TopicAnswerService: create(dto)
activate TopicAnswerService

TopicAnswerService -> BaseService: create(dto) << Inherited from Parent >>
activate BaseService

BaseService -> TopicAnswerService: convertToEntity(dto) << Overridden >>
activate TopicAnswerService
TopicAnswerService -> TopicAnswerService: convertToEntity(dto)
TopicAnswerService --> BaseService: TopicAnswerEntity
deactivate TopicAnswerService

BaseService -> Entity: setId(null)

BaseService -> Repository: save(entity)
activate Repository
Repository --> BaseService: savedEntity
deactivate Repository

BaseService -> TopicAnswerService: convertToDTO(entity) << Overridden >>
activate TopicAnswerService
TopicAnswerService -> TopicAnswerService: convertToDTO(entity)
TopicAnswerService --> BaseService: TopicAnswerDTO
deactivate TopicAnswerService

BaseService --> TopicAnswerService: savedDTO
deactivate BaseService

TopicAnswerService --> Teacher: TopicAnswerDTO
deactivate TopicAnswerService

@enduml
