@startuml updateTopicAnswer

actor Teacher
participant "TopicAnswerServiceImpl" as TopicAnswerService
participant "BaseServiceImpl" as BaseService
participant "TopicAnswerRepository" as Repository


== Lược đồ tuần tự chức năng chỉnh sửa đáp án chủ đề ==
Teacher -> TopicAnswerService: update(dto, id)
activate TopicAnswerService

TopicAnswerService -> BaseService: update(dto, id) << Inherited from Parent >>
activate BaseService

BaseService -> BaseService: isExist(id)
BaseService -> TopicAnswerService: convertToEntity(dto) << Overridden >>
activate TopicAnswerService
TopicAnswerService -> TopicAnswerService: convertToEntity(dto)
TopicAnswerService --> BaseService: TopicAnswerEntity
deactivate TopicAnswerService

BaseService -> Repository: save(entity)
activate Repository
Repository --> BaseService: Updated Entity
deactivate Repository

BaseService -> TopicAnswerService: convertToDTO(updatedEntity) << Overridden >>
activate TopicAnswerService
TopicAnswerService -> TopicAnswerService: convertToDTO(updatedEntity)
TopicAnswerService --> BaseService: Converted DTO
deactivate TopicAnswerService

BaseService --> TopicAnswerService: Updated DTO
deactivate BaseService

TopicAnswerService --> Teacher: Updated DTO
deactivate TopicAnswerService

@enduml
