@startuml deleteListeningAnswer

actor Teacher
participant "ListeningAnswerServiceImpl" as ListeningAnswerService
participant "BaseServiceImpl" as BaseService
participant "ListeningAnswerRepository" as Repository

== Lược đồ tuần tự chức năng xoá câu trả lời của câu hỏi bài học nghe ==
Teacher -> ListeningAnswerService: delete(id)
activate ListeningAnswerService

ListeningAnswerService -> BaseService: delete(id) << Inherited from Parent >>
activate BaseService

BaseService -> BaseService: isExist(id)
BaseService -> Repository: deleteById(id)
activate Repository
Repository --> BaseService: Deleted ListeningAnswerEntity
deactivate Repository

BaseService --> ListeningAnswerService: Deleted ListeningAnswerDTO
deactivate BaseService

ListeningAnswerService --> Teacher: Deleted ListeningAnswerDTO
deactivate ListeningAnswerService

@enduml
