@startuml updateListeningQuestion

actor Teacher
participant "ListeningQuestionServiceImpl" as ListeningQuestionService
participant "BaseServiceImpl" as BaseService
participant "ListeningQuestionRepository" as Repository


== Lược đồ tuần tự chức năng chỉnh sửa câu hỏi bài học nghe ==
Teacher -> ListeningQuestionService: update(dto, id)
activate ListeningQuestionService

ListeningQuestionService -> ListeningQuestionService: isSerialUnique(dto.getListeningId(), dto.getSerial(), id)
ListeningQuestionService -> BaseService: update(dto, id) << Inherited from Parent >>
activate BaseService

BaseService -> BaseService: isExist(id)
BaseService -> ListeningQuestionService: convertToEntity(dto) << Overridden >>
activate ListeningQuestionService
ListeningQuestionService --> BaseService: ListeningQuestionEntity
deactivate ListeningQuestionService

BaseService -> Repository: save(entity)
activate Repository
Repository --> BaseService: Updated ListeningQuestionEntity
deactivate Repository

BaseService -> ListeningQuestionService: convertToDTO(updatedEntity) << Overridden >>
activate ListeningQuestionService
ListeningQuestionService --> BaseService: ListeningQuestionDTO
deactivate ListeningQuestionService

BaseService --> ListeningQuestionService: Updated ListeningQuestionDTO
deactivate BaseService

ListeningQuestionService --> Teacher: Updated ListeningQuestionDTO
deactivate ListeningQuestionService

@enduml
