@startuml updateListeningAnswer

actor Teacher
participant "ListeningAnswerServiceImpl" as ListeningAnswerService
participant "BaseServiceImpl" as BaseService
participant "ListeningAnswerRepository" as Repository


== Lược đồ tuần tự chức năng chỉnh sửa câu trả lời của câu hỏi bài học nghe ==
Teacher -> ListeningAnswerService: update(dto, id)
activate ListeningAnswerService

ListeningAnswerService -> BaseService: update(dto, id) << Inherited from Parent >>
activate BaseService

BaseService -> BaseService: isExist(id)
BaseService -> ListeningAnswerService: convertToEntity(dto) << Overridden >>
activate ListeningAnswerService
ListeningAnswerService --> BaseService: ListeningAnswerEntity
deactivate ListeningAnswerService

BaseService -> Repository: save(updatedEntity)
activate Repository
Repository --> BaseService: Updated ListeningAnswerEntity
deactivate Repository

BaseService -> ListeningAnswerService: convertToDTO(updatedEntity) << Overridden >>
activate ListeningAnswerService
ListeningAnswerService --> BaseService: Updated ListeningAnswerDTO
deactivate ListeningAnswerService

BaseService --> ListeningAnswerService: Updated ListeningAnswerDTO
deactivate BaseService

ListeningAnswerService --> Teacher: Updated ListeningAnswerDTO
deactivate ListeningAnswerService

@enduml
