@startuml findBySpeakingId

actor Teacher
participant "SpeakingConversationServiceImpl" as SpeakingConversationService
participant "SpeakingServiceImpl" as SpeakingService
participant "SpeakingConversationRepository" as Repository


== Lược đồ tuần tự chức năng lấy thông tin cuộc hội thoại của bài học nói ==
Teacher -> SpeakingConversationService: findBySpeakingId(speakingId)
activate SpeakingConversationService

SpeakingConversationService -> SpeakingService: isExist(speakingId)
activate SpeakingService
SpeakingService --> SpeakingConversationService: Speaking exists
deactivate SpeakingService

SpeakingConversationService -> Repository: findAllBySpeaking_Id(speakingId)
activate Repository
Repository --> SpeakingConversationService: List<SpeakingConversation>
deactivate Repository

SpeakingConversationService -> SpeakingConversationService: convertToDTO(entity)
activate SpeakingConversationService
SpeakingConversationService --> SpeakingConversationService: Converted DTO
deactivate SpeakingConversationService

SpeakingConversationService --> Teacher: List<SpeakingConversationDTO>
deactivate SpeakingConversationService

@enduml
