@startuml updateSpeaking

actor Teacher
participant "SpeakingServiceImpl" as SpeakingService
participant "BaseServiceImpl" as BaseService
participant "SpeakingRepository" as Repository

== Lược đồ tuần tự chức năng chỉnh sửa bài học nói. ==
Teacher -> SpeakingService: update(dto, id)
activate SpeakingService

SpeakingService -> BaseService: update(dto, id) << Inherited from Parent >>
activate BaseService

BaseService -> BaseService: isExist(id)
BaseService -> SpeakingService: convertToEntity(dto) << Overridden >>
activate SpeakingService
SpeakingService -> SpeakingService: convertToEntity(dto)
SpeakingService --> BaseService: SpeakingEntity
deactivate SpeakingService

BaseService -> Repository: save(updatedEntity)
activate Repository
Repository --> BaseService: Updated SpeakingEntity
deactivate Repository

BaseService -> SpeakingService: convertToDTO(updatedEntity) << Overridden >>
activate SpeakingService
SpeakingService -> SpeakingService: convertToDTO(updatedEntity)
SpeakingService --> BaseService: Converted SpeakingDTO
deactivate SpeakingService

BaseService --> SpeakingService: Updated SpeakingDTO
deactivate BaseService

SpeakingService --> Teacher: Updated SpeakingDTO
deactivate SpeakingService

@enduml
