@startuml createTestReading
actor Teacher
participant "TestReadingServiceImpl" as TestReadingService
participant "BaseServiceImpl" as BaseService
participant "TestReadingRepository" as Repository

== Lược đồ tuần tự chức năng thêm bài kiểm tra đọc  ==
Teacher -> TestReadingService: create(dto)
activate TestReadingService

TestReadingService -> BaseService: create(dto) << Inherited from Parent >>
activate BaseService

BaseService -> TestReadingService: convertToEntity(dto) << Overridden >>
activate TestReadingService
TestReadingService --> BaseService: TestReadingEntity
deactivate TestReadingService

BaseService -> Repository: save(entity)
activate Repository
Repository --> BaseService: Saved Entity
deactivate Repository

BaseService -> TestReadingService: convertToDTO(entity) << Overridden >>
activate TestReadingService
TestReadingService --> BaseService: TestReadingDTO
deactivate TestReadingService

BaseService --> TestReadingService: Saved DTO
deactivate BaseService

TestReadingService --> Teacher: TestReadingDTO
deactivate TestReadingService

@enduml
