@startuml createTestWriting
actor Teacher
participant "TestWritingServiceImpl" as TestWritingService
participant "BaseServiceImpl" as BaseService
participant "TestWritingRepository" as Repository

== Lược đồ tuần tự chức năng thêm bài kiểm tra viết  ==
Teacher -> TestWritingService: create(dto)
activate TestWritingService

TestWritingService -> BaseService: create(dto) << Inherited from Parent >>
activate BaseService

BaseService -> TestWritingService: convertToEntity(dto) << Overridden >>
activate TestWritingService
TestWritingService --> BaseService: TestWritingEntity
deactivate TestWritingService

BaseService -> Repository: save(entity)
activate Repository
Repository --> BaseService: Saved Entity
deactivate Repository

BaseService -> TestWritingService: convertToDTO(entity) << Overridden >>
activate TestWritingService
TestWritingService --> BaseService: TestWritingDTO
deactivate TestWritingService

BaseService --> TestWritingService: Saved DTO
deactivate BaseService

TestWritingService --> Teacher: TestWritingDTO
deactivate TestWritingService

@enduml
