@startuml createTestSpeaking
actor Teacher
participant "TestSpeakingServiceImpl" as TestSpeakingService
participant "BaseServiceImpl" as BaseService
participant "TestSpeakingRepository" as Repository

== 	Lược đồ tuần tự chức năng thêm bài kiểm tra nói  ==
Teacher -> TestSpeakingService: create(dto)
activate TestSpeakingService

TestSpeakingService -> BaseService: create(dto) << Inherited from Parent >>
activate BaseService

BaseService -> TestSpeakingService: convertToEntity(dto) << Overridden >>
activate TestSpeakingService
TestSpeakingService --> BaseService: TestSpeakingEntity
deactivate TestSpeakingService

BaseService -> Repository: save(entity)
activate Repository
Repository --> BaseService: Saved Entity
deactivate Repository

BaseService -> TestSpeakingService: convertToDTO(entity) << Overridden >>
activate TestSpeakingService
TestSpeakingService --> BaseService: TestSpeakingDTO
deactivate TestSpeakingService

BaseService --> TestSpeakingService: Saved DTO
deactivate BaseService

TestSpeakingService --> Teacher: TestSpeakingDTO
deactivate TestSpeakingService

@enduml
