@startuml createTestMixingQuestion
actor Teacher
participant "TestMixingQuestionServiceImpl" as TestMixingQuestionService
participant "BaseServiceImpl" as BaseService
participant "TestMixingQuestionRepository" as Repository

== Lược đồ tuần tự chức năng thêm câu hỏi kiểm tra từ vựng hoặc ngữ pháp ==
Teacher -> TestMixingQuestionService: create(dto)
activate TestMixingQuestionService

TestMixingQuestionService -> BaseService: create(dto) << Inherited from Parent >>
activate BaseService

BaseService -> TestMixingQuestionService: convertToEntity(dto) << Overridden >>
activate TestMixingQuestionService
TestMixingQuestionService --> BaseService: TestMixingQuestionEntity
deactivate TestMixingQuestionService

BaseService -> Repository: save(entity)
activate Repository
Repository --> BaseService: Saved Entity
deactivate Repository

BaseService -> TestMixingQuestionService: convertToDTO(entity) << Overridden >>
activate TestMixingQuestionService
TestMixingQuestionService --> BaseService: TestMixingQuestionDTO
deactivate TestMixingQuestionService

BaseService --> TestMixingQuestionService: Saved DTO
deactivate BaseService

TestMixingQuestionService --> Teacher: TestMixingQuestionDTO
deactivate TestMixingQuestionService

@enduml
