@startuml createTestReadingQuestion
actor Teacher
participant "TestReadingQuestionServiceImpl" as TestReadingQuestionService
participant "BaseServiceImpl" as BaseService
participant "TestReadingQuestionRepository" as Repository

== Lược đồ tuần tự chức năng thêm câu hỏi của bài kiểm tra đọc ==
Teacher -> TestReadingQuestionService: create(dto)
activate TestReadingQuestionService

TestReadingQuestionService -> BaseService: create(dto) << Inherited from Parent >>
activate BaseService

BaseService -> TestReadingQuestionService: convertToEntity(dto) << Overridden >>
activate TestReadingQuestionService
TestReadingQuestionService --> BaseService: TestReadingQuestionEntity
deactivate TestReadingQuestionService

BaseService -> Repository: save(entity)
activate Repository
Repository --> BaseService: Saved Entity
deactivate Repository

BaseService -> TestReadingQuestionService: convertToDTO(entity) << Overridden >>
activate TestReadingQuestionService
TestReadingQuestionService --> BaseService: TestReadingQuestionDTO
deactivate TestReadingQuestionService

BaseService --> TestReadingQuestionService: Saved DTO
deactivate BaseService

TestReadingQuestionService --> Teacher: TestReadingQuestionDTO
deactivate TestReadingQuestionService

@enduml
