@startuml createTestListeningAnswer
actor Teacher
participant "TestListeningAnswerServiceImpl" as TestListeningAnswerService
participant "BaseServiceImpl" as BaseService
participant "TestListeningAnswerRepository" as Repository

== Lược đồ tuần tự chức năng thêm câu trả lời của câu hỏi của bài kiểm tra nghe ==
Teacher -> TestListeningAnswerService: create(dto)
activate TestListeningAnswerService

TestListeningAnswerService -> BaseService: create(dto) << Inherited from Parent >>
activate BaseService

BaseService -> TestListeningAnswerService: convertToEntity(dto) << Overridden >>
activate TestListeningAnswerService
TestListeningAnswerService --> BaseService: TestListeningAnswerEntity
deactivate TestListeningAnswerService

BaseService -> Repository: save(entity)
activate Repository
Repository --> BaseService: Saved Entity
deactivate Repository

BaseService -> TestListeningAnswerService: convertToDTO(entity) << Overridden >>
activate TestListeningAnswerService
TestListeningAnswerService --> BaseService: TestListeningAnswerDTO
deactivate TestListeningAnswerService

BaseService --> TestListeningAnswerService: Saved DTO
deactivate BaseService

TestListeningAnswerService --> Teacher: TestListeningAnswerDTO
deactivate TestListeningAnswerService

@enduml
