@startuml createTest
participant PageListTest
participant TestController
participant "TestServiceImpl" as TestService
participant "BaseServiceImpl" as BaseService
participant "TestRepository" as Repository

== Lược đồ tuần tự chức năng thêm bài kiểm tra ==


PageListTest -> TestController: POST /api/test {TestDTO}
activate TestController

TestController -> TestService: create(dto)
activate TestService

TestService -> BaseService: create(dto) << Inherited from Parent >>
activate BaseService

BaseService -> TestService: convertToEntity(dto) << Overridden >>
activate TestService
TestService --> BaseService: TestEntity
deactivate TestService

BaseService -> Repository: save(entity)
activate Repository
Repository --> BaseService: Saved Entity
deactivate Repository

BaseService -> TestService: convertToDTO(entity) << Overridden >>
activate TestService
TestService --> BaseService: TestDTO
deactivate TestService

BaseService --> TestService: Saved DTO
deactivate BaseService

TestService --> TestController: TestDTO
deactivate TestService


TestController --> PageListTest: Response (201 Created, {TestDTO})
deactivate TestController
@enduml
