@startuml createTestListeningQuestion
actor Teacher
participant "TestListeningQuestionServiceImpl" as TestListeningQuestionService
participant "BaseServiceImpl" as BaseService
participant "TestListeningQuestionRepository" as Repository

== Lược đồ tuần tự chức năng thêm câu hỏi của bài kiểm tra nghe ==
Teacher -> TestListeningQuestionService: create(dto)
activate TestListeningQuestionService

TestListeningQuestionService -> BaseService: create(dto) << Inherited from Parent >>
activate BaseService

BaseService -> TestListeningQuestionService: convertToEntity(dto) << Overridden >>
activate TestListeningQuestionService
TestListeningQuestionService --> BaseService: TestListeningQuestionEntity
deactivate TestListeningQuestionService

BaseService -> Repository: save(entity)
activate Repository
Repository --> BaseService: Saved Entity
deactivate Repository

BaseService -> TestListeningQuestionService: convertToDTO(entity) << Overridden >>
activate TestListeningQuestionService
TestListeningQuestionService --> BaseService: TestListeningQuestionDTO
deactivate TestListeningQuestionService

BaseService --> TestListeningQuestionService: Saved DTO
deactivate BaseService

TestListeningQuestionService --> Teacher: TestListeningQuestionDTO
deactivate TestListeningQuestionService

@enduml
