@startuml createTestReadingAnswer
actor Teacher
participant "TestReadingAnswerServiceImpl" as TestReadingAnswerService
participant "BaseServiceImpl" as BaseService
participant "TestReadingAnswerRepository" as Repository

== Lược đồ tuần tự chức năng thêm câu trả lời của câu hỏi của bài kiểm tra đọc  ==
Teacher -> TestReadingAnswerService: create(dto)
activate TestReadingAnswerService

TestReadingAnswerService -> BaseService: create(dto) << Inherited from Parent >>
activate BaseService

BaseService -> TestReadingAnswerService: convertToEntity(dto) << Overridden >>
activate TestReadingAnswerService
TestReadingAnswerService --> BaseService: TestReadingAnswerEntity
deactivate TestReadingAnswerService

BaseService -> Repository: save(entity)
activate Repository
Repository --> BaseService: Saved Entity
deactivate Repository

BaseService -> TestReadingAnswerService: convertToDTO(entity) << Overridden >>
activate TestReadingAnswerService
TestReadingAnswerService --> BaseService: TestReadingAnswerDTO
deactivate TestReadingAnswerService

BaseService --> TestReadingAnswerService: Saved DTO
deactivate BaseService

TestReadingAnswerService --> Teacher: TestReadingAnswerDTO
deactivate TestReadingAnswerService

@enduml
