@startuml createTestSpeakingQuestion

actor Teacher
participant "TestSpeakingQuestionServiceImpl" as TestSpeakingQuestionService
participant "BaseServiceImpl" as BaseService
participant "TestSpeakingQuestionRepository" as Repository



== Lược đồ tuần tự chức năng thêm câu hỏi của bài kiểm tra nói ==
Teacher -> TestSpeakingQuestionService: create(dto)
activate TestSpeakingQuestionService

TestSpeakingQuestionService -> BaseService: create(dto) << Inherited from Parent >>
activate BaseService

BaseService -> TestSpeakingQuestionService: convertToEntity(dto) << Overridden >>
activate TestSpeakingQuestionService
TestSpeakingQuestionService --> BaseService: TestSpeakingQuestionEntity
deactivate TestSpeakingQuestionService



BaseService -> Repository: save(entity)
activate Repository
Repository --> BaseService: Saved TestSpeakingQuestionEntity
deactivate Repository

BaseService -> TestSpeakingQuestionService: convertToDTO(savedEntity) << Overridden >>
activate TestSpeakingQuestionService
TestSpeakingQuestionService --> BaseService: TestSpeakingQuestionDTO
deactivate TestSpeakingQuestionService

BaseService --> TestSpeakingQuestionService: Saved TestSpeakingQuestionDTO
deactivate BaseService

TestSpeakingQuestionService --> Teacher: TestSpeakingQuestionDTO
deactivate TestSpeakingQuestionService

@enduml
