@startuml deleteTestListeningAnswer
actor Teacher
participant "TestListeningAnswerServiceImpl" as TestListeningAnswerService
participant "BaseServiceImpl" as BaseService
participant "TestListeningAnswerRepository" as Repository

== Lược đồ tuần tự chức năng xoá câu trả lời của câu hỏi của bài kiểm tra nghe ==
Teacher -> TestListeningAnswerService: delete(id)
activate TestListeningAnswerService

TestListeningAnswerService -> BaseService: delete(id) << Inherited from Parent >>
activate BaseService

BaseService -> BaseService: isExist(id)
BaseService -> Repository: deleteById(id)
activate Repository
Repository --> BaseService: Entity deleted
deactivate Repository

BaseService --> TestListeningAnswerService: Deletion complete
deactivate BaseService

TestListeningAnswerService --> Teacher: Deletion complete
deactivate TestListeningAnswerService

@enduml
