@startuml deleteTestReadingAnswer
actor Teacher
participant "TestReadingAnswerServiceImpl" as TestReadingAnswerService
participant "BaseServiceImpl" as BaseService
participant "TestReadingAnswerRepository" as Repository

== Lược đồ tuần tự chức năng xoá câu trả lời của câu hỏi của bài kiểm tra đọc ==
Teacher -> TestReadingAnswerService: delete(id)
activate TestReadingAnswerService

TestReadingAnswerService -> BaseService: delete(id) << Inherited from Parent >>
activate BaseService

BaseService -> BaseService: isExist(id)
BaseService -> Repository: deleteById(id)
activate Repository
Repository --> BaseService: Entity deleted
deactivate Repository

BaseService --> TestReadingAnswerService: Deletion complete
deactivate BaseService

TestReadingAnswerService --> Teacher: Deletion complete
deactivate TestReadingAnswerService

@enduml
