@startuml deleteTestReadingQuestion

actor Teacher
participant "TestReadingQuestionServiceImpl" as TestReadingQuestionService
participant "TestReadingAnswerServiceImpl" as TestReadingAnswerService
participant "BaseServiceImpl" as BaseService
par
== Lược đồ tuần tự chức năng xoá câu hỏi của bài kiểm tra nghe ==
Teacher -> TestReadingQuestionService: delete(id)
activate TestReadingQuestionService

TestReadingQuestionService -> TestReadingAnswerService: findAllByQuestionId(id)
activate TestReadingAnswerService
TestReadingAnswerService --> TestReadingQuestionService: List<TestReadingAnswerDTO>
deactivate TestReadingAnswerService

alt If answers exist
    loop Delete TestReadingAnswers
        TestReadingQuestionService -> TestReadingAnswerService: delete(answer.getId())
        activate TestReadingAnswerService
        TestReadingAnswerService --> TestReadingQuestionService: Deletion complete
        deactivate TestReadingAnswerService
    end
end

TestReadingQuestionService -> BaseService: delete(id) << Inherited from Parent >>
activate BaseService
BaseService --> TestReadingQuestionService: Entity deleted
deactivate BaseService

TestReadingQuestionService --> Teacher: Deletion complete
deactivate TestReadingQuestionService

@enduml
