@startuml deleteTestReading

actor Teacher
participant "TestReadingServiceImpl" as TestReadingService
participant "TestReadingQuestionServiceImpl" as TestReadingQuestionService
participant "BaseServiceImpl" as BaseService

== Lược đồ tuần tự chức năng xoá bài kiểm tra đọc ==
Teacher -> TestReadingService: delete(id)
activate TestReadingService

TestReadingService -> TestReadingQuestionService: findAllByTestReading_Id(id)
activate TestReadingQuestionService
TestReadingQuestionService --> TestReadingService: List<TestReadingQuestionDTO>
deactivate TestReadingQuestionService

alt If questions exist
    loop Delete TestReadingQuestions
        TestReadingService -> TestReadingQuestionService: delete(question.getId())
        activate TestReadingQuestionService
        TestReadingQuestionService --> TestReadingService: Deletion complete
        deactivate TestReadingQuestionService
    end
end

TestReadingService -> BaseService: delete(id) << Inherited from Parent >>
activate BaseService
BaseService --> TestReadingService: Entity deleted
deactivate BaseService

TestReadingService --> Teacher: Deletion complete
deactivate TestReadingService

@enduml
