@startuml deleteTestSpeaking

actor Teacher
participant "TestSpeakingServiceImpl" as TestSpeakingService
participant "TestSpeakingQuestionServiceImpl" as TestSpeakingQuestionService
participant "BaseServiceImpl" as BaseService

== Lược đồ tuần tự chức năng xoá bài kiểm tra nói ==
Teacher -> TestSpeakingService: delete(id)
activate TestSpeakingService

TestSpeakingService -> TestSpeakingQuestionService: findAllByTestSpeaking_Id(id)
activate TestSpeakingQuestionService
TestSpeakingQuestionService --> TestSpeakingService: List<TestSpeakingQuestionDTO>
deactivate TestSpeakingQuestionService

alt If questions exist
    loop Delete TestSpeakingQuestions
        TestSpeakingService -> TestSpeakingQuestionService: delete(question.getId())
        activate TestSpeakingQuestionService
        TestSpeakingQuestionService --> TestSpeakingService: Deletion complete
        deactivate TestSpeakingQuestionService
    end
end

TestSpeakingService -> BaseService: delete(id) << Inherited from Parent >>
activate BaseService
BaseService --> TestSpeakingService: Entity deleted
deactivate BaseService

TestSpeakingService --> Teacher: Deletion complete
deactivate TestSpeakingService

@enduml
