@startuml updateTestWriting
actor Teacher
participant "TestWritingServiceImpl" as TestWritingService
participant "BaseServiceImpl" as BaseService
participant "TestWritingRepository" as Repository

== Lược đồ tuần tự chức năng chỉnh sửa bài kiểm tra viết ==
Teacher -> TestWritingService: update(dto, id)
activate TestWritingService

TestWritingService -> BaseService: update(dto, id) << Inherited from Parent >>
activate BaseService

BaseService -> BaseService: isExist(id)
BaseService -> TestWritingService: convertToEntity(dto) << Overridden >>
activate TestWritingService
TestWritingService --> BaseService: TestWritingEntity
deactivate TestWritingService

BaseService -> Repository: save(entity)
activate Repository
Repository --> BaseService: Updated Entity
deactivate Repository

BaseService -> TestWritingService: convertToDTO(updatedEntity) << Overridden >>
activate TestWritingService
TestWritingService --> BaseService: TestWritingDTO
deactivate TestWritingService

BaseService --> TestWritingService: Updated DTO
deactivate BaseService

TestWritingService --> Teacher: Updated DTO
deactivate TestWritingService

@enduml
