@startuml updateTestListeningQuestion
actor Teacher
participant "TestListeningQuestionServiceImpl" as TestListeningQuestionService
participant "BaseServiceImpl" as BaseService
participant "TestListeningQuestionRepository" as Repository

== Lược đồ tuần tự chức năng chỉnh sửa câu hỏi của bài kiểm tra nghe ==
Teacher -> TestListeningQuestionService: update(dto, id)
activate TestListeningQuestionService

TestListeningQuestionService -> BaseService: update(dto, id) << Inherited from Parent >>
activate BaseService

BaseService -> BaseService: isExist(id)
BaseService -> TestListeningQuestionService: convertToEntity(dto) << Overridden >>
activate TestListeningQuestionService
TestListeningQuestionService --> BaseService: TestListeningQuestionEntity
deactivate TestListeningQuestionService

BaseService -> Repository: save(entity)
activate Repository
Repository --> BaseService: Updated Entity
deactivate Repository

BaseService -> TestListeningQuestionService: convertToDTO(updatedEntity) << Overridden >>
activate TestListeningQuestionService
TestListeningQuestionService --> BaseService: TestListeningQuestionDTO
deactivate TestListeningQuestionService

BaseService --> TestListeningQuestionService: Updated DTO
deactivate BaseService

TestListeningQuestionService --> Teacher: Updated DTO
deactivate TestListeningQuestionService

@enduml
