@startuml Create

actor User
participant "BaseServiceImpl" as BSI
participant "Repository" as REP

== Create Entity ==
User -> BSI: create(dto)
activate BSI

BSI -> BSI: convertToEntity(dto)
note right: convertToEntity được triển khai trong lớp con
BSI -> REP: Save entity
activate REP
REP --> BSI: Saved entity
deactivate REP

BSI -> BSI: convertToDTO(saved entity)
note right: convertToDTO được triển khai trong lớp con
BSI --> User: Return saved DTO
deactivate BSI

@enduml
