@startuml Delete

actor User
participant "BaseServiceImpl" as BSI
participant "Repository" as REP

== Delete Entity ==
User -> BSI: delete(id)
activate BSI

BSI -> BSI: isExist(id)
BSI -> REP: Delete entity by ID
activate REP
REP --> BSI: Entity deleted
deactivate REP

BSI --> User: Confirm deletion
deactivate BSI

@enduml
