@startuml ConvertToDTO

participant "BaseServiceImpl" as BSI
participant "ListenAndWriteAWordServiceImpl" as LWS

== Convert Entity to DTO ==
BSI -> LWS: convertToDTO(entity)
note right: convertToDTO được triển khai trong ListenAndWriteAWordServiceImpl
activate LWS
LWS --> BSI: ListenAndWriteAWordDTO
deactivate LWS

@enduml
