@startuml deleteGrammarAnswer

actor Teacher
participant "GrammarAnswerServiceImpl" as GrammarAnswerService
participant "BaseServiceImpl" as BaseService
participant "GrammarAnswerRepository" as Repository

== Lược đồ tuần tự chức năng xoá câu trả lời ngữ pháp ==
Teacher -> GrammarAnswerService: delete(id)
activate GrammarAnswerService

GrammarAnswerService -> BaseService: delete(id) << Inherited from Parent >>
activate BaseService

BaseService -> BaseService: isExist(id)
BaseService -> Repository: deleteById(id)
activate Repository
Repository --> BaseService: Deleted Entity
deactivate Repository

BaseService --> GrammarAnswerService: Deleted Successfully
deactivate BaseService

GrammarAnswerService --> Teacher: Deleted Successfully
deactivate GrammarAnswerService

@enduml
