@startuml findAllByGrammarIdAndStatus

actor Teacher
participant "GrammarQuestionServiceImpl" as GrammarQuestionService
participant "GrammarServiceImpl" as GrammarService
participant "GrammarQuestionRepository" as Repository

== Lược đồ tuần tự chức năng tìm danh sách câu hỏi và câu trả lời của bài học ngữ pháp ==
Teacher -> GrammarQuestionService: findAllByGrammarIdAndStatus(grammarId, status)
activate GrammarQuestionService

alt Status is null
    GrammarQuestionService -> GrammarQuestionService: findAllByGrammarId(grammarId)
     activate GrammarQuestionService
   GrammarQuestionService --> Teacher: List<GrammarQuestionDTO>
        deactivate GrammarQuestionService
else Status is not null
    GrammarQuestionService -> GrammarService: isExist(grammarId)
    activate GrammarService
    GrammarService --> GrammarQuestionService: Grammar exists
    deactivate GrammarService

    GrammarQuestionService -> Repository: findAllByGrammar_IdAndStatus(grammarId, status)
    activate Repository
    Repository --> GrammarQuestionService: List<GrammarQuestion>
    deactivate Repository

    loop Convert entities to DTOs and Filter answers
        GrammarQuestionService -> GrammarQuestionService: convertToDTO(entity)
        activate GrammarQuestionService
        GrammarQuestionService --> GrammarQuestionService: Converted GrammarQuestionDTO
        deactivate GrammarQuestionService

        GrammarQuestionService -> GrammarQuestionService: Filter answers by status
        activate GrammarQuestionService
        GrammarQuestionService --> GrammarQuestionService: Updated GrammarQuestionDTO
        deactivate GrammarQuestionService
    end
end

GrammarQuestionService --> Teacher: List<GrammarQuestionDTO>
deactivate GrammarQuestionService

@enduml
