@startuml updateGrammar

actor Teacher
participant "GrammarServiceImpl" as GrammarService
participant "BaseServiceImpl" as BaseService
participant "GrammarRepository" as Repository


== Lược đồ tuần tự chức năng cập nhật  bài học ngữ pháp ==
Teacher -> GrammarService: update(dto, id)
activate GrammarService

GrammarService -> BaseService: update(dto, id) << Inherited from Parent >>
activate BaseService

BaseService -> BaseService: isExist(id)

BaseService -> GrammarService: convertToEntity(dto) << Overridden >>
activate GrammarService
GrammarService -> GrammarService: convertToEntity(dto)
GrammarService --> BaseService: GrammarEntity
deactivate GrammarService

BaseService -> Repository: save(updatedEntity)
activate Repository
Repository --> BaseService: Updated GrammarEntity
deactivate Repository

BaseService -> GrammarService: convertToDTO(updatedEntity) << Overridden >>
activate GrammarService
GrammarService -> GrammarService: convertToDTO(updatedEntity)
GrammarService --> BaseService: Updated GrammarDTO
deactivate GrammarService

BaseService --> GrammarService: Updated GrammarDTO
deactivate BaseService

GrammarService --> Teacher: Updated GrammarDTO
deactivate GrammarService

@enduml
