@startuml updateGrammarAnswer

actor Teacher
participant "GrammarAnswerServiceImpl" as GrammarAnswerService
participant "BaseServiceImpl" as BaseService
participant "GrammarAnswerRepository" as Repository

== Lược đồ tuần tự chức năng chỉnh sửa câu trả lời ngữ pháp ==
Teacher -> GrammarAnswerService: update(dto, id)
activate GrammarAnswerService

GrammarAnswerService -> BaseService: update(dto, id) << Inherited from Parent >>
activate BaseService

BaseService -> BaseService: isExist(id)
BaseService -> GrammarAnswerService: convertToEntity(dto) << Overridden >>
activate GrammarAnswerService
GrammarAnswerService -> GrammarAnswerService: convertToEntity(dto)
GrammarAnswerService --> BaseService: Converted Entity
deactivate GrammarAnswerService

BaseService -> Repository: save(entity)
activate Repository
Repository --> BaseService: Updated Entity
deactivate Repository

BaseService -> GrammarAnswerService: convertToDTO(updatedEntity) << Overridden >>
activate GrammarAnswerService
GrammarAnswerService -> GrammarAnswerService: convertToDTO(updatedEntity)
GrammarAnswerService --> BaseService: Converted DTO
deactivate GrammarAnswerService

BaseService --> GrammarAnswerService: Updated DTO
deactivate BaseService

GrammarAnswerService --> Teacher: Updated DTO
deactivate GrammarAnswerService

@enduml
