@startuml findByIdWritingService

actor Student
participant "WritingServiceImpl" as WritingService
participant "BaseServiceImpl" as BaseService
participant "WritingRepository" as Repository

== Lược đồ tuần tự chức năng lấy thông tin bài viết ==
Student -> WritingService: findById(id)
activate WritingService
WritingService -> BaseService: findById(id) << Inherited from Parent >>
activate BaseService
BaseService -> BaseService: isExist(id)
BaseService -> Repository: findById(id)
activate Repository
Repository --> BaseService: WritingEntity
deactivate Repository
BaseService -> WritingService: convertToDTO(WritingEntity) << Overridden >>
activate WritingService
WritingService -> WritingService: convertToDTO(WritingEntity)
WritingService --> BaseService: WritingDTO
deactivate WritingService
BaseService --> WritingService: WritingDTO
deactivate BaseService
WritingService --> Student: WritingDTO
deactivate WritingService

@enduml
