@startuml deleteWriting

actor Teacher
participant "WritingServiceImpl" as WritingService
participant "BaseServiceImpl" as BaseService
participant "WritingRepository" as Repository

== Lược đồ tuần tự chức năng xoá bài học viết ==
Teacher -> WritingService: delete(id)
activate WritingService

WritingService -> BaseService: delete(id) << Inherited from Parent >>
activate BaseService

BaseService -> BaseService: isExist(id)
BaseService -> Repository: deleteById(id)
activate Repository
Repository --> BaseService: Deleted WritingEntity
deactivate Repository

BaseService --> WritingService: Deleted WritingDTO
deactivate BaseService

WritingService --> Teacher: Deleted WritingDTO
deactivate WritingService

@enduml
